![](https://full-stack-assets.s3.eu-west-3.amazonaws.com/apple-logo.png)

# Apple Retail Store - From CSV to Mongo

## Business context

Apple's leadership wants a unified analytics backend in MongoDB to answer:

1. Revenue by **category** and **region** (monthly trend)
2. **Top products** by revenue (last 90 days)
3. **Store** performance month-over-month (MoM)
4. **Warranty** coverage & average duration by category
5. **ASP vs list price** sanity check by category

Data sources (CSV):

* `products.csv` — product catalog: `product_id, name, category_id, brand, list_price`
* `category.csv` — categories: `category_id, category_name, parent_id?`
* `stores.csv` — stores: `store_id, store_name, city, region, country`
* `sales.csv` — **big** fact table: `sale_id, product_id, store_id, date, units_sold, total_amount` (≥ 1M rows)
* `warranty.csv` — warranty info: `product_id, duration_months`

## Part I - Insert small data

In [ ]:
#!pip install -q xgboost
#!pip install -q s3fs
#!pip install -U kaleido
#!pip install Boto3
#!pip install s3fs
# Load in our libraries
#pip install pymongo[srv]
#pip install dotenv
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import json
import os
# import s3fs
#import boto3

# plotly
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.io as pio
import plotly.figure_factory as ff
import plotly.colors as pc

# setting Jedha color palette as default
pio.templates["jedha"] = go.layout.Template(
    layout_colorway=["#4B9AC7", "#4BE8E0", "#9DD4F3", "#97FBF6", "#2A7FAF", "#23B1AB", "#0E3449", "#015955"]
)
pio.templates.default = "jedha"
pio.renderers.default = "colab" # pour que colab ne bloque pas l'export svg

import warnings
warnings.filterwarnings('ignore')



# montage drive
from google.colab import drive
drive.mount('/content/drive')

Requirement already satisfied: pymongo[srv] in /usr/local/lib/python3.12/dist-packages (4.16.0)
WARNING: pymongo 4.16.0 does not provide the extra 'srv'
Requirement already satisfied: dnspython<3.0.0,>=2.6.1 in /usr/local/lib/python3.12/dist-packages (from pymongo[srv]) (2.8.0)
Requirement already satisfied: dotenv in /usr/local/lib/python3.12/dist-packages (0.9.9)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.12/dist-packages (from dotenv) (1.2.1)
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# 1️⃣ Imports corrects
from google.colab import userdata
from pymongo import MongoClient
from pymongo.server_api import ServerApi

# 2️⃣ Installer pymongo DANS Colab (avant l'import si ce n'est pas déjà fait)
%pip install pymongo[srv]

Requirement already satisfied: pymongo[srv] in /usr/local/lib/python3.12/dist-packages (4.16.0)
WARNING: pymongo 4.16.0 does not provide the extra 'srv'
Requirement already satisfied: dnspython<3.0.0,>=2.6.1 in /usr/local/lib/python3.12/dist-packages (from pymongo[srv]) (2.8.0)

In [ ]:

# 3️⃣ Récupération des secrets Colab
USERNAME = userdata.get("MONGO_USERNAME")
PASSWORD = userdata.get("PASSWORD")
CLUSTER = userdata.get("CLUSTER_NAME")


# Vérification explicite
if not all([USERNAME, PASSWORD, CLUSTER]):
    raise ValueError("Un ou plusieurs secrets Colab sont manquants")

print(f"Hello {CLUSTER}")

# URI MongoDB CORRECTE
MONGODB_URI = (
    f"mongodb+srv://{USERNAME}:{PASSWORD}@{CLUSTER}/"
    "?retryWrites=true&w=majority&appName=Cluster0"
)

# Connexion
client = MongoClient(MONGODB_URI, server_api=ServerApi("1"))

client.admin.command("ping")
print("Pinged your deployment. You successfully connected to MongoDB!")

Hello cluster0.u9zhept.mongodb.net
Pinged your deployment. You successfully connected to MongoDB!

1. Create a virtual environment and install dependencies.

2. Set your Mongo URI (Atlas or local):

For the following, we recommend organizing your project like so:

```
apple_exercise/
  data/
    products.csv
    category.csv
    stores.csv
    sales.csv
    warranty.csv
  apple_exercise.ipynb   # put the code from the next parts here
```

3. Using `pandas` load the following datasets:
    - `products`
    - `categories`
    - `stores`
    - `warranties`

In [ ]:
# Chargement des fichiers CSV (dimensions)
files = [

]
products = pd.read_csv("/content/drive/MyDrive/JedhaBootcamp/products.csv")
categories = pd.read_csv("/content/drive/MyDrive/JedhaBootcamp/categories.csv")
stores = pd.read_csv("/content/drive/MyDrive/JedhaBootcamp/stores.csv")
warranties = pd.read_csv("/content/drive/MyDrive/JedhaBootcamp/warranties.csv")

# Vérification rapide
print("Products shape:", products.shape)
print("Categories shape:", categories.shape)
print("Stores shape:", stores.shape)
print("Warranties shape:", warranties.shape)

# Aperçu des données
display(products.head())
display(categories.head())
display(stores.head())
display(warranties.head())

Products shape: (89, 5)
Categories shape: (10, 2)
Stores shape: (75, 4)
Warranties shape: (30000, 4)

  Product_ID         Product_Name Category_ID Launch_Date  Price
0        P-1              MacBook       CAT-1  2023-09-17   1149
1        P-2     MacBook Air (M1)       CAT-1  2023-11-11   1783
2        P-3     MacBook Air (M2)       CAT-1  2020-05-24   1588
3        P-4  MacBook Pro 13-inch       CAT-1  2021-01-17   1351
4        P-5  MacBook Pro 14-inch       CAT-1  2024-05-12    768

  category_id category_name
0       CAT-1        Laptop
1       CAT-2         Audio
2       CAT-3        Tablet
3       CAT-4    Smartphone
4       CAT-5      Wearable

  Store_ID             Store_Name           City        Country
0     ST-1     Apple Fifth Avenue       New York  United States
1     ST-2     Apple Union Square  San Francisco  United States
2     ST-3  Apple Michigan Avenue        Chicago  United States
3     ST-4        Apple The Grove    Los Angeles  United States
4     ST-5             Apple SoHo       New York  United States

   claim_id  claim_date    sale_id repair_status
0  CL-58750  2024-01-30    YG-8782     Completed
1   CL-8874  2024-06-25  QX-999001       Pending
2  CL-14486  2024-08-13   JG-46890       Pending
3  CL-42187  2024-09-19    XJ-1731       Pending
4  CL-37590  2024-09-16   FG-95080     Completed

4. Create helper function that:
    - Normalize columns data. Meaning:
        - all columns should be lower case
        - No spaces, only `_`
        - No special characters

    - Apply on all data

In [ ]:
import re

def normalize_columns(df):
    df.columns = (
        df.columns
        .str.lower()
        .str.strip()
        .str.replace(" ", "_")
        .str.replace(r"[^a-z0-9_]", "", regex=True)
    )
    return df

In [ ]:
products = normalize_columns(products)
categories = normalize_columns(categories)
stores = normalize_columns(stores)
warranties = normalize_columns(warranties)

In [ ]:
display(products.head())
display(categories.head())
display(stores.head())
display(warranties.head())

  product_id         product_name category_id launch_date  price
0        P-1              MacBook       CAT-1  2023-09-17   1149
1        P-2     MacBook Air (M1)       CAT-1  2023-11-11   1783
2        P-3     MacBook Air (M2)       CAT-1  2020-05-24   1588
3        P-4  MacBook Pro 13-inch       CAT-1  2021-01-17   1351
4        P-5  MacBook Pro 14-inch       CAT-1  2024-05-12    768

  category_id category_name
0       CAT-1        Laptop
1       CAT-2         Audio
2       CAT-3        Tablet
3       CAT-4    Smartphone
4       CAT-5      Wearable

  store_id             store_name           city        country
0     ST-1     Apple Fifth Avenue       New York  United States
1     ST-2     Apple Union Square  San Francisco  United States
2     ST-3  Apple Michigan Avenue        Chicago  United States
3     ST-4        Apple The Grove    Los Angeles  United States
4     ST-5             Apple SoHo       New York  United States

   claim_id  claim_date    sale_id repair_status
0  CL-58750  2024-01-30    YG-8782     Completed
1   CL-8874  2024-06-25  QX-999001       Pending
2  CL-14486  2024-08-13   JG-46890       Pending
3  CL-42187  2024-09-19    XJ-1731       Pending
4  CL-37590  2024-09-16   FG-95080     Completed

4. Cast columns of each columns to the most relevant datatype (i.e `str` or `float` etc.)

5. Create a new database called `apple_retail_store` with the right collections:

- `products`
- `categories`
- `stores`
- `warranties`

In [ ]:
client = MongoClient(MONGODB_URI)
db = client["apple_retail_store"]

from pymongo import MongoClient
MONGODB_URI

client = MongoClient(MONGODB_URI)
db = client["apple_retail_store"]

6. Insert data from each dataframes inside its corresponding collection

In [ ]:
db.products.drop()
db.categories.drop()
db.stores.drop()
db.warranties.drop()
db.sales.drop

<bound method Collection.drop of Collection(Database(MongoClient(host=['ac-zkn1wi5-shard-00-02.u9zhept.mongodb.net:27017', 'ac-zkn1wi5-shard-00-01.u9zhept.mongodb.net:27017', 'ac-zkn1wi5-shard-00-00.u9zhept.mongodb.net:27017'], document_class=dict, tz_aware=False, connect=True, retrywrites=True, w='majority', appname='Cluster0', authsource='admin', replicaset='atlas-kvjhh5-shard-0', tls=True), 'apple_retail_store'), 'sales')>

In [ ]:
db.products.insert_many(products.to_dict("records"))
db.categories.insert_many(categories.to_dict("records"))
db.stores.insert_many(stores.to_dict("records"))
db.warranties.insert_many(warranties.to_dict("records"))

InsertManyResult([ObjectId('696146ca1446c7d285737848'), ObjectId('696146ca1446c7d285737849'), ObjectId('696146ca1446c7d28573784a'), ObjectId('696146ca1446c7d28573784b'), ObjectId('696146ca1446c7d28573784c'), ObjectId('696146ca1446c7d28573784d'), ObjectId('696146ca1446c7d28573784e'), ObjectId('696146ca1446c7d28573784f'), ObjectId('696146ca1446c7d285737850'), ObjectId('696146ca1446c7d285737851'), ObjectId('696146ca1446c7d285737852'), ObjectId('696146ca1446c7d285737853'), ObjectId('696146ca1446c7d285737854'), ObjectId('696146ca1446c7d285737855'), ObjectId('696146ca1446c7d285737856'), ObjectId('696146ca1446c7d285737857'), ObjectId('696146ca1446c7d285737858'), ObjectId('696146ca1446c7d285737859'), ObjectId('696146ca1446c7d28573785a'), ObjectId('696146ca1446c7d28573785b'), ObjectId('696146ca1446c7d28573785c'), ObjectId('696146ca1446c7d28573785d'), ObjectId('696146ca1446c7d28573785e'), ObjectId('696146ca1446c7d28573785f'), ObjectId('696146ca1446c7d285737860'), ObjectId('696146ca1446c7d285737861'), ObjectId('696146ca1446c7d285737862'), ObjectId('696146ca1446c7d285737863'), ObjectId('696146ca1446c7d285737864'), ObjectId('696146ca1446c7d285737865'), ObjectId('696146ca1446c7d285737866'), ObjectId('696146ca1446c7d285737867'), ObjectId('696146ca1446c7d285737868'), ObjectId('696146ca1446c7d285737869'), ObjectId('696146ca1446c7d28573786a'), ObjectId('696146ca1446c7d28573786b'), ObjectId('696146ca1446c7d28573786c'), ObjectId('696146ca1446c7d28573786d'), ObjectId('696146ca1446c7d28573786e'), ObjectId('696146ca1446c7d28573786f'), ObjectId('696146ca1446c7d285737870'), ObjectId('696146ca1446c7d285737871'), ObjectId('696146ca1446c7d285737872'), ObjectId('696146ca1446c7d285737873'), ObjectId('696146ca1446c7d285737874'), ObjectId('696146ca1446c7d285737875'), ObjectId('696146ca1446c7d285737876'), ObjectId('696146ca1446c7d285737877'), ObjectId('696146ca1446c7d285737878'), ObjectId('696146ca1446c7d285737879'), ObjectId('696146ca1446c7d28573787a'), ObjectId('696146ca1446c7d28573787b'), ObjectId('696146ca1446c7d28573787c'), ObjectId('696146ca1446c7d28573787d'), ObjectId('696146ca1446c7d28573787e'), ObjectId('696146ca1446c7d28573787f'), ObjectId('696146ca1446c7d285737880'), ObjectId('696146ca1446c7d285737881'), ObjectId('696146ca1446c7d285737882'), ObjectId('696146ca1446c7d285737883'), ObjectId('696146ca1446c7d285737884'), ObjectId('696146ca1446c7d285737885'), ObjectId('696146ca1446c7d285737886'), ObjectId('696146ca1446c7d285737887'), ObjectId('696146ca1446c7d285737888'), ObjectId('696146ca1446c7d285737889'), ObjectId('696146ca1446c7d28573788a'), ObjectId('696146ca1446c7d28573788b'), ObjectId('696146ca1446c7d28573788c'), ObjectId('696146ca1446c7d28573788d'), ObjectId('696146ca1446c7d28573788e'), ObjectId('696146ca1446c7d28573788f'), ObjectId('696146ca1446c7d285737890'), ObjectId('696146ca1446c7d285737891'), ObjectId('696146ca1446c7d285737892'), ObjectId('696146ca1446c7d285737893'), ObjectId('696146ca1446c7d285737894'), ObjectId('696146ca1446c7d285737895'), ObjectId('696146ca1446c7d285737896'), ObjectId('696146ca1446c7d285737897'), ObjectId('696146ca1446c7d285737898'), ObjectId('696146ca1446c7d285737899'), ObjectId('696146ca1446c7d28573789a'), ObjectId('696146ca1446c7d28573789b'), ObjectId('696146ca1446c7d28573789c'), ObjectId('696146ca1446c7d28573789d'), ObjectId('696146ca1446c7d28573789e'), ObjectId('696146ca1446c7d28573789f'), ObjectId('696146ca1446c7d2857378a0'), ObjectId('696146ca1446c7d2857378a1'), ObjectId('696146ca1446c7d2857378a2'), ObjectId('696146ca1446c7d2857378a3'), ObjectId('696146ca1446c7d2857378a4'), ObjectId('696146ca1446c7d2857378a5'), ObjectId('696146ca1446c7d2857378a6'), ObjectId('696146ca1446c7d2857378a7'), ObjectId('696146ca1446c7d2857378a8'), ObjectId('696146ca1446c7d2857378a9'), ObjectId('696146ca1446c7d2857378aa'), ObjectId('696146ca1446c7d2857378ab'), ObjectId('696146ca1446c7d2857378ac'), ObjectId('696146ca1446c7d2857378ad'), ObjectId('696146ca1446c7d2857378ae'), ObjectId('696146ca1446c7d2857378af'), ObjectId('696146ca1446c7d2857378b0'), ObjectId('696146ca1446c7d2857378b1'), ObjectId('696146ca1446c7d2857378b2'), ObjectId('696146ca1446c7d2857378b3'), ObjectId('696146ca1446c7d2857378b4'), ObjectId('696146ca1446c7d2857378b5'), ObjectId('696146ca1446c7d2857378b6'), ObjectId('696146ca1446c7d2857378b7'), ObjectId('696146ca1446c7d2857378b8'), ObjectId('696146ca1446c7d2857378b9'), ObjectId('696146ca1446c7d2857378ba'), ObjectId('696146ca1446c7d2857378bb'), ObjectId('696146ca1446c7d2857378bc'), ObjectId('696146ca1446c7d2857378bd'), ObjectId('696146ca1446c7d2857378be'), ObjectId('696146ca1446c7d2857378bf'), ObjectId('696146ca1446c7d2857378c0'), ObjectId('696146ca1446c7d2857378c1'), ObjectId('696146ca1446c7d2857378c2'), ObjectId('696146ca1446c7d2857378c3'), ObjectId('696146ca1446c7d2857378c4'), ObjectId('696146ca1446c7d2857378c5'), ObjectId('696146ca1446c7d2857378c6'), ObjectId('696146ca1446c7d2857378c7'), ObjectId('696146ca1446c7d2857378c8'), ObjectId('696146ca1446c7d2857378c9'), ObjectId('696146ca1446c7d2857378ca'), ObjectId('696146ca1446c7d2857378cb'), ObjectId('696146ca1446c7d2857378cc'), ObjectId('696146ca1446c7d2857378cd'), ObjectId('696146ca1446c7d2857378ce'), ObjectId('696146ca1446c7d2857378cf'), ObjectId('696146ca1446c7d2857378d0'), ObjectId('696146ca1446c7d2857378d1'), ObjectId('696146ca1446c7d2857378d2'), ObjectId('696146ca1446c7d2857378d3'), ObjectId('696146ca1446c7d2857378d4'), ObjectId('696146ca1446c7d2857378d5'), ObjectId('696146ca1446c7d2857378d6'), ObjectId('696146ca1446c7d2857378d7'), ObjectId('696146ca1446c7d2857378d8'), ObjectId('696146ca1446c7d2857378d9'), ObjectId('696146ca1446c7d2857378da'), ObjectId('696146ca1446c7d2857378db'), ObjectId('696146ca1446c7d2857378dc'), ObjectId('696146ca1446c7d2857378dd'), ObjectId('696146ca1446c7d2857378de'), ObjectId('696146ca1446c7d2857378df'), ObjectId('696146ca1446c7d2857378e0'), ObjectId('696146ca1446c7d2857378e1'), ObjectId('696146ca1446c7d2857378e2'), ObjectId('696146ca1446c7d2857378e3'), ObjectId('696146ca1446c7d2857378e4'), ObjectId('696146ca1446c7d2857378e5'), ObjectId('696146ca1446c7d2857378e6'), ObjectId('696146ca1446c7d2857378e7'), ObjectId('696146ca1446c7d2857378e8'), ObjectId('696146ca1446c7d2857378e9'), ObjectId('696146ca1446c7d2857378ea'), ObjectId('696146ca1446c7d2857378eb'), ObjectId('696146ca1446c7d2857378ec'), ObjectId('696146ca1446c7d2857378ed'), ObjectId('696146ca1446c7d2857378ee'), ObjectId('696146ca1446c7d2857378ef'), ObjectId('696146ca1446c7d2857378f0'), ObjectId('696146ca1446c7d2857378f1'), ObjectId('696146ca1446c7d2857378f2'), ObjectId('696146ca1446c7d2857378f3'), ObjectId('696146ca1446c7d2857378f4'), ObjectId('696146ca1446c7d2857378f5'), ObjectId('696146ca1446c7d2857378f6'), ObjectId('696146ca1446c7d2857378f7'), ObjectId('696146ca1446c7d2857378f8'), ObjectId('696146ca1446c7d2857378f9'), ObjectId('696146ca1446c7d2857378fa'), ObjectId('696146ca1446c7d2857378fb'), ObjectId('696146ca1446c7d2857378fc'), ObjectId('696146ca1446c7d2857378fd'), ObjectId('696146ca1446c7d2857378fe'), ObjectId('696146ca1446c7d2857378ff'), ObjectId('696146ca1446c7d285737900'), ObjectId('696146ca1446c7d285737901'), ObjectId('696146ca1446c7d285737902'), ObjectId('696146ca1446c7d285737903'), ObjectId('696146ca1446c7d285737904'), ObjectId('696146ca1446c7d285737905'), ObjectId('696146ca1446c7d285737906'), ObjectId('696146ca1446c7d285737907'), ObjectId('696146ca1446c7d285737908'), ObjectId('696146ca1446c7d285737909'), ObjectId('696146ca1446c7d28573790a'), ObjectId('696146ca1446c7d28573790b'), ObjectId('696146ca1446c7d28573790c'), ObjectId('696146ca1446c7d28573790d'), ObjectId('696146ca1446c7d28573790e'), ObjectId('696146ca1446c7d28573790f'), ObjectId('696146ca1446c7d285737910'), ObjectId('696146ca1446c7d285737911'), ObjectId('696146ca1446c7d285737912'), ObjectId('696146ca1446c7d285737913'), ObjectId('696146ca1446c7d285737914'), ObjectId('696146ca1446c7d285737915'), ObjectId('696146ca1446c7d285737916'), ObjectId('696146ca1446c7d285737917'), ObjectId('696146ca1446c7d285737918'), ObjectId('696146ca1446c7d285737919'), ObjectId('696146ca1446c7d28573791a'), ObjectId('696146ca1446c7d28573791b'), ObjectId('696146ca1446c7d28573791c'), ObjectId('696146ca1446c7d28573791d'), ObjectId('696146ca1446c7d28573791e'), ObjectId('696146ca1446c7d28573791f'), ObjectId('696146ca1446c7d285737920'), ObjectId('696146ca1446c7d285737921'), ObjectId('696146ca1446c7d285737922'), ObjectId('696146ca1446c7d285737923'), ObjectId('696146ca1446c7d285737924'), ObjectId('696146ca1446c7d285737925'), ObjectId('696146ca1446c7d285737926'), ObjectId('696146ca1446c7d285737927'), ObjectId('696146ca1446c7d285737928'), ObjectId('696146ca1446c7d285737929'), ObjectId('696146ca1446c7d28573792a'), ObjectId('696146ca1446c7d28573792b'), ObjectId('696146ca1446c7d28573792c'), ObjectId('696146ca1446c7d28573792d'), ObjectId('696146ca1446c7d28573792e'), ObjectId('696146ca1446c7d28573792f'), ObjectId('696146ca1446c7d285737930'), ObjectId('696146ca1446c7d285737931'), ObjectId('696146ca1446c7d285737932'), ObjectId('696146ca1446c7d285737933'), ObjectId('696146ca1446c7d285737934'), ObjectId('696146ca1446c7d285737935'), ObjectId('696146ca1446c7d285737936'), ObjectId('696146ca1446c7d285737937'), ObjectId('696146ca1446c7d285737938'), ObjectId('696146ca1446c7d285737939'), ObjectId('696146ca1446c7d28573793a'), ObjectId('696146ca1446c7d28573793b'), ObjectId('696146ca1446c7d28573793c'), ObjectId('696146ca1446c7d28573793d'), ObjectId('696146ca1446c7d28573793e'), ObjectId('696146ca1446c7d28573793f'), ObjectId('696146ca1446c7d285737940'), ObjectId('696146ca1446c7d285737941'), ObjectId('696146ca1446c7d285737942'), ObjectId('696146ca1446c7d285737943'), ObjectId('696146ca1446c7d285737944'), ObjectId('696146ca1446c7d285737945'), ObjectId('696146ca1446c7d285737946'), ObjectId('696146ca1446c7d285737947'), ObjectId('696146ca1446c7d285737948'), ObjectId('696146ca1446c7d285737949'), ObjectId('696146ca1446c7d28573794a'), ObjectId('696146ca1446c7d28573794b'), ObjectId('696146ca1446c7d28573794c'), ObjectId('696146ca1446c7d28573794d'), ObjectId('696146ca1446c7d28573794e'), ObjectId('696146ca1446c7d28573794f'), ObjectId('696146ca1446c7d285737950'), ObjectId('696146ca1446c7d285737951'), ObjectId('696146ca1446c7d285737952'), ObjectId('696146ca1446c7d285737953'), ObjectId('696146ca1446c7d285737954'), ObjectId('696146ca1446c7d285737955'), ObjectId('696146ca1446c7d285737956'), ObjectId('696146ca1446c7d285737957'), ObjectId('696146ca1446c7d285737958'), ObjectId('696146ca1446c7d285737959'), ObjectId('696146ca1446c7d28573795a'), ObjectId('696146ca1446c7d28573795b'), ObjectId('696146ca1446c7d28573795c'), ObjectId('696146ca1446c7d28573795d'), ObjectId('696146ca1446c7d28573795e'), ObjectId('696146ca1446c7d28573795f'), ObjectId('696146ca1446c7d285737960'), ObjectId('696146ca1446c7d285737961'), ObjectId('696146ca1446c7d285737962'), ObjectId('696146ca1446c7d285737963'), ObjectId('696146ca1446c7d285737964'), ObjectId('696146ca1446c7d285737965'), ObjectId('696146ca1446c7d285737966'), ObjectId('696146ca1446c7d285737967'), ObjectId('696146ca1446c7d285737968'), ObjectId('696146ca1446c7d285737969'), ObjectId('696146ca1446c7d28573796a'), ObjectId('696146ca1446c7d28573796b'), ObjectId('696146ca1446c7d28573796c'), ObjectId('696146ca1446c7d28573796d'), ObjectId('696146ca1446c7d28573796e'), ObjectId('696146ca1446c7d28573796f'), ObjectId('696146ca1446c7d285737970'), ObjectId('696146ca1446c7d285737971'), ObjectId('696146ca1446c7d285737972'), ObjectId('696146ca1446c7d285737973'), ObjectId('696146ca1446c7d285737974'), ObjectId('696146ca1446c7d285737975'), ObjectId('696146ca1446c7d285737976'), ObjectId('696146ca1446c7d285737977'), ObjectId('696146ca1446c7d285737978'), ObjectId('696146ca1446c7d285737979'), ObjectId('696146ca1446c7d28573797a'), ObjectId('696146ca1446c7d28573797b'), ObjectId('696146ca1446c7d28573797c'), ObjectId('696146ca1446c7d28573797d'), ObjectId('696146ca1446c7d28573797e'), ObjectId('696146ca1446c7d28573797f'), ObjectId('696146ca1446c7d285737980'), ObjectId('696146ca1446c7d285737981'), ObjectId('696146ca1446c7d285737982'), ObjectId('696146ca1446c7d285737983'), ObjectId('696146ca1446c7d285737984'), ObjectId('696146ca1446c7d285737985'), ObjectId('696146ca1446c7d285737986'), ObjectId('696146ca1446c7d285737987'), ObjectId('696146ca1446c7d285737988'), ObjectId('696146ca1446c7d285737989'), ObjectId('696146ca1446c7d28573798a'), ObjectId('696146ca1446c7d28573798b'), ObjectId('696146ca1446c7d28573798c'), ObjectId('696146ca1446c7d28573798d'), ObjectId('696146ca1446c7d28573798e'), ObjectId('696146ca1446c7d28573798f'), ObjectId('696146ca1446c7d285737990'), ObjectId('696146ca1446c7d285737991'), ObjectId('696146ca1446c7d285737992'), ObjectId('696146ca1446c7d285737993'), ObjectId('696146ca1446c7d285737994'), ObjectId('696146ca1446c7d285737995'), ObjectId('696146ca1446c7d285737996'), ObjectId('696146ca1446c7d285737997'), ObjectId('696146ca1446c7d285737998'), ObjectId('696146ca1446c7d285737999'), ObjectId('696146ca1446c7d28573799a'), ObjectId('696146ca1446c7d28573799b'), ObjectId('696146ca1446c7d28573799c'), ObjectId('696146ca1446c7d28573799d'), ObjectId('696146ca1446c7d28573799e'), ObjectId('696146ca1446c7d28573799f'), ObjectId('696146ca1446c7d2857379a0'), ObjectId('696146ca1446c7d2857379a1'), ObjectId('696146ca1446c7d2857379a2'), ObjectId('696146ca1446c7d2857379a3'), ObjectId('696146ca1446c7d2857379a4'), ObjectId('696146ca1446c7d2857379a5'), ObjectId('696146ca1446c7d2857379a6'), ObjectId('696146ca1446c7d2857379a7'), ObjectId('696146ca1446c7d2857379a8'), ObjectId('696146ca1446c7d2857379a9'), ObjectId('696146ca1446c7d2857379aa'), ObjectId('696146ca1446c7d2857379ab'), ObjectId('696146ca1446c7d2857379ac'), ObjectId('696146ca1446c7d2857379ad'), ObjectId('696146ca1446c7d2857379ae'), ObjectId('696146ca1446c7d2857379af'), ObjectId('696146ca1446c7d2857379b0'), ObjectId('696146ca1446c7d2857379b1'), ObjectId('696146ca1446c7d2857379b2'), ObjectId('696146ca1446c7d2857379b3'), ObjectId('696146ca1446c7d2857379b4'), ObjectId('696146ca1446c7d2857379b5'), ObjectId('696146ca1446c7d2857379b6'), ObjectId('696146ca1446c7d2857379b7'), ObjectId('696146ca1446c7d2857379b8'), ObjectId('696146ca1446c7d2857379b9'), ObjectId('696146ca1446c7d2857379ba'), ObjectId('696146ca1446c7d2857379bb'), ObjectId('696146ca1446c7d2857379bc'), ObjectId('696146ca1446c7d2857379bd'), ObjectId('696146ca1446c7d2857379be'), ObjectId('696146ca1446c7d2857379bf'), ObjectId('696146ca1446c7d2857379c0'), ObjectId('696146ca1446c7d2857379c1'), ObjectId('696146ca1446c7d2857379c2'), ObjectId('696146ca1446c7d2857379c3'), ObjectId('696146ca1446c7d2857379c4'), ObjectId('696146ca1446c7d2857379c5'), ObjectId('696146ca1446c7d2857379c6'), ObjectId('696146ca1446c7d2857379c7'), ObjectId('696146ca1446c7d2857379c8'), ObjectId('696146ca1446c7d2857379c9'), ObjectId('696146ca1446c7d2857379ca'), ObjectId('696146ca1446c7d2857379cb'), ObjectId('696146ca1446c7d2857379cc'), ObjectId('696146ca1446c7d2857379cd'), ObjectId('696146ca1446c7d2857379ce'), ObjectId('696146ca1446c7d2857379cf'), ObjectId('696146ca1446c7d2857379d0'), ObjectId('696146ca1446c7d2857379d1'), ObjectId('696146ca1446c7d2857379d2'), ObjectId('696146ca1446c7d2857379d3'), ObjectId('696146ca1446c7d2857379d4'), ObjectId('696146ca1446c7d2857379d5'), ObjectId('696146ca1446c7d2857379d6'), ObjectId('696146ca1446c7d2857379d7'), ObjectId('696146ca1446c7d2857379d8'), ObjectId('696146ca1446c7d2857379d9'), ObjectId('696146ca1446c7d2857379da'), ObjectId('696146ca1446c7d2857379db'), ObjectId('696146ca1446c7d2857379dc'), ObjectId('696146ca1446c7d2857379dd'), ObjectId('696146ca1446c7d2857379de'), ObjectId('696146ca1446c7d2857379df'), ObjectId('696146ca1446c7d2857379e0'), ObjectId('696146ca1446c7d2857379e1'), ObjectId('696146ca1446c7d2857379e2'), ObjectId('696146ca1446c7d2857379e3'), ObjectId('696146ca1446c7d2857379e4'), ObjectId('696146ca1446c7d2857379e5'), ObjectId('696146ca1446c7d2857379e6'), ObjectId('696146ca1446c7d2857379e7'), ObjectId('696146ca1446c7d2857379e8'), ObjectId('696146ca1446c7d2857379e9'), ObjectId('696146ca1446c7d2857379ea'), ObjectId('696146ca1446c7d2857379eb'), ObjectId('696146ca1446c7d2857379ec'), ObjectId('696146ca1446c7d2857379ed'), ObjectId('696146ca1446c7d2857379ee'), ObjectId('696146ca1446c7d2857379ef'), ObjectId('696146ca1446c7d2857379f0'), ObjectId('696146ca1446c7d2857379f1'), ObjectId('696146ca1446c7d2857379f2'), ObjectId('696146ca1446c7d2857379f3'), ObjectId('696146ca1446c7d2857379f4'), ObjectId('696146ca1446c7d2857379f5'), ObjectId('696146ca1446c7d2857379f6'), ObjectId('696146ca1446c7d2857379f7'), ObjectId('696146ca1446c7d2857379f8'), ObjectId('696146ca1446c7d2857379f9'), ObjectId('696146ca1446c7d2857379fa'), ObjectId('696146ca1446c7d2857379fb'), ObjectId('696146ca1446c7d2857379fc'), ObjectId('696146ca1446c7d2857379fd'), ObjectId('696146ca1446c7d2857379fe'), ObjectId('696146ca1446c7d2857379ff'), ObjectId('696146ca1446c7d285737a00'), ObjectId('696146ca1446c7d285737a01'), ObjectId('696146ca1446c7d285737a02'), ObjectId('696146ca1446c7d285737a03'), ObjectId('696146ca1446c7d285737a04'), ObjectId('696146ca1446c7d285737a05'), ObjectId('696146ca1446c7d285737a06'), ObjectId('696146ca1446c7d285737a07'), ObjectId('696146ca1446c7d285737a08'), ObjectId('696146ca1446c7d285737a09'), ObjectId('696146ca1446c7d285737a0a'), ObjectId('696146ca1446c7d285737a0b'), ObjectId('696146ca1446c7d285737a0c'), ObjectId('696146ca1446c7d285737a0d'), ObjectId('696146ca1446c7d285737a0e'), ObjectId('696146ca1446c7d285737a0f'), ObjectId('696146ca1446c7d285737a10'), ObjectId('696146ca1446c7d285737a11'), ObjectId('696146ca1446c7d285737a12'), ObjectId('696146ca1446c7d285737a13'), ObjectId('696146ca1446c7d285737a14'), ObjectId('696146ca1446c7d285737a15'), ObjectId('696146ca1446c7d285737a16'), ObjectId('696146ca1446c7d285737a17'), ObjectId('696146ca1446c7d285737a18'), ObjectId('696146ca1446c7d285737a19'), ObjectId('696146ca1446c7d285737a1a'), ObjectId('696146ca1446c7d285737a1b'), ObjectId('696146ca1446c7d285737a1c'), ObjectId('696146ca1446c7d285737a1d'), ObjectId('696146ca1446c7d285737a1e'), ObjectId('696146ca1446c7d285737a1f'), ObjectId('696146ca1446c7d285737a20'), ObjectId('696146ca1446c7d285737a21'), ObjectId('696146ca1446c7d285737a22'), ObjectId('696146ca1446c7d285737a23'), ObjectId('696146ca1446c7d285737a24'), ObjectId('696146ca1446c7d285737a25'), ObjectId('696146ca1446c7d285737a26'), ObjectId('696146ca1446c7d285737a27'), ObjectId('696146ca1446c7d285737a28'), ObjectId('696146ca1446c7d285737a29'), ObjectId('696146ca1446c7d285737a2a'), ObjectId('696146ca1446c7d285737a2b'), ObjectId('696146ca1446c7d285737a2c'), ObjectId('696146ca1446c7d285737a2d'), ObjectId('696146ca1446c7d285737a2e'), ObjectId('696146ca1446c7d285737a2f'), ObjectId('696146ca1446c7d285737a30'), ObjectId('696146ca1446c7d285737a31'), ObjectId('696146ca1446c7d285737a32'), ObjectId('696146ca1446c7d285737a33'), ObjectId('696146ca1446c7d285737a34'), ObjectId('696146ca1446c7d285737a35'), ObjectId('696146ca1446c7d285737a36'), ObjectId('696146ca1446c7d285737a37'), ObjectId('696146ca1446c7d285737a38'), ObjectId('696146ca1446c7d285737a39'), ObjectId('696146ca1446c7d285737a3a'), ObjectId('696146ca1446c7d285737a3b'), ObjectId('696146ca1446c7d285737a3c'), ObjectId('696146ca1446c7d285737a3d'), ObjectId('696146ca1446c7d285737a3e'), ObjectId('696146ca1446c7d285737a3f'), ObjectId('696146ca1446c7d285737a40'), ObjectId('696146ca1446c7d285737a41'), ObjectId('696146ca1446c7d285737a42'), ObjectId('696146ca1446c7d285737a43'), ObjectId('696146ca1446c7d285737a44'), ObjectId('696146ca1446c7d285737a45'), ObjectId('696146ca1446c7d285737a46'), ObjectId('696146ca1446c7d285737a47'), ObjectId('696146ca1446c7d285737a48'), ObjectId('696146ca1446c7d285737a49'), ObjectId('696146ca1446c7d285737a4a'), ObjectId('696146ca1446c7d285737a4b'), ObjectId('696146ca1446c7d285737a4c'), ObjectId('696146ca1446c7d285737a4d'), ObjectId('696146ca1446c7d285737a4e'), ObjectId('696146ca1446c7d285737a4f'), ObjectId('696146ca1446c7d285737a50'), ObjectId('696146ca1446c7d285737a51'), ObjectId('696146ca1446c7d285737a52'), ObjectId('696146ca1446c7d285737a53'), ObjectId('696146ca1446c7d285737a54'), ObjectId('696146ca1446c7d285737a

## Part II - Insert Big Data

Okay let's do something harder now, the `sales.csv` contains more than 1 million rows. So it will harder to insert it in MongoDB since it will require much more compute power. Don't worry, there are some technics though 😉

<Note type="hint">

In `pd.read_csv` there is a parameter called `chunksize` this lets you process data in batch. Each chunk needs to be considered as an interator of a for loop:

```python

for chunk in df = pd.read_csv("path", chunksize=100_000):
    #CODE
```

Have fun with it!

</Note>

1. Normalize the columns of the CSV

In [ ]:
chunksize = 100_000

for chunk in pd.read_csv("/content/drive/MyDrive/JedhaBootcamp/sales.csv", chunksize=chunksize):
    chunk = normalize_columns(chunk)
    chunk["sale_id"] = chunk["sale_id"].astype(str)
    chunk["sale_date"] = chunk["sale_date"].astype(str)
    chunk["store_id"] = chunk["store_id"].astype(str)
    chunk["product_id"] = chunk["product_id"].astype(str)
    chunk["quantity"] = chunk["quantity"].astype(int)
    chunk["quantity"] = chunk["quantity"].astype(int)
    db.sales.insert_many(chunk.to_dict("records"))

2. Cast each columns to its right data type

3. Now insert that data inside your db

## Part 3 - Create indexes

1. For each collection, think and create indexes that might be relevant for analytics

In [ ]:
db.products.create_index(
    "product_id",
    unique=True,
    partialFilterExpression={
        "product_id": {
            "$exists": True,
            "$type": "string"
        }
    }
)

'product_id_1'

In [ ]:

db.products.create_index("category_id")

'category_id_1'

In [ ]:
db.products.count_documents({"product_id": None})

0

In [ ]:
db.categories.create_index("category_id", unique=True)

'category_id_1'

In [ ]:
db.stores.create_index("store_id", unique=True)
db.stores.create_index("country")

'country_1'

In [ ]:
db.sales.create_index([("sale_date", 1)])
db.sales.create_index([("product_id", 1)])
db.sales.create_index([("store_id", 1)])
db.sales.create_index([ ("store_id", 1), ("sale_date", 1)])

'sale_date_1_store_id_1'

In [ ]:
db.warranties.create_index("sale_id")
db.warranties.create_index("repair_status")

'repair_status_1'